version: "3.2"

services:
  # backend
  backend:
    container_name: pokemol-backend
    build: ./backend
    restart: always
    env_file: .env
    ports:
      - "${SERVER_PORT}:3000"
    expose:
      - "${SERVER_PORT}"
    depends_on:
      - mongo-db
    links:
      - mongo-db

  # MongoDB
  mongo-db:
    container_name: pokemol-mongo
    image: mongo:latest
    restart: always
    env_file: .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - './mongo:/docker-entrypoint-initdb.d'

volumes:
  mongo:
    driver: local